---
  - name: Install mysqld python libary for Ansible
    package:
      name: '{{ mysql_python_package }}'
      state: present


  - name: remove remote root
    community.mysql.mysql_query:
      query:
        - DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')
      login_unix_socket: "{{ login_unix_socket | default(omit) }}"
    when: mysql_remove_remote_root


  - name: test database is absent
    mysql_db:
      name: test
      state: absent
      login_unix_socket: "{{ login_unix_socket | default(omit) }}"
    when: mysql_remove_test_database


  - name: anonymous users are absent
    mysql_user:
      name: ''
      state: absent
      host_all: true
      login_unix_socket: "{{ login_unix_socket | default(omit) }}"
    when: mysql_remove_anonymous_users